#!/usr/bin/env python3
"""Render results/**/*.json into RESULTS.md.

RESULTS.md is generated. Never edit it by hand -- CI regenerates it and fails
the PR if the committed file differs.

The central idea here is that there are two different kinds of variance, and
collapsing them into one number destroys the information:

  * TIME VARIANCE  -- same host_id, different hours. Noisy neighbours.
    Answers: "is this machine consistent throughout the day?"

  * HOST VARIANCE  -- different host_id, same product+region. Fleet spread.
    Answers: "does this provider hand out consistent machines?"

Averaging either one away is how you end up with a table claiming a provider is
fine when it is fine at 03:00 and unusable at 18:00. So: median AND worst,
always, and never a mean.

Usage:
    python3 tools/render.py > RESULTS.md
"""
from __future__ import annotations

import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"

MARK = {"pass": "pass", "marginal": "marginal", "fail": "fail", "unknown": "?", None: "?"}
PROFILES = ["postgres_oltp", "timescale_ingest", "redis_aof", "nuxt_ssr"]

# Below this many runs we do not compute a spread. Two points is not a
# distribution, it is a line segment.
MIN_RUNS_FOR_SPREAD = 3

DISCLAIMER = (
    "*Every number below is a measurement of specific machines at specific times. "
    "Providers vary by region, by hardware generation within a region, and by who "
    "else is on the host. Read [METHODOLOGY.md](METHODOLOGY.md) before drawing "
    "conclusions, and [THRESHOLDS.md](THRESHOLDS.md) before disagreeing with a "
    "verdict.*"
)


def fmt_us(v) -> str:
    """Microseconds stop being readable past a few thousand."""
    if v is None:
        return "-"
    if v >= 1000:
        return f"{v/1000:.1f} ms"
    return f"{v:.0f} us"


def fmt_pct(v) -> str:
    return "-" if v is None else f"{v:.1f}%"


def dig(o, path, default=None):
    cur = o
    for p in path.split("."):
        if not isinstance(cur, dict) or p not in cur or cur[p] is None:
            return default
        cur = cur[p]
    return cur


def load_all() -> list[dict]:
    out = []
    if not RESULTS.exists():
        return out
    for f in sorted(RESULTS.rglob("*.json")):
        try:
            d = json.loads(f.read_text())
            d["_path"] = str(f.relative_to(ROOT))
            out.append(d)
        except json.JSONDecodeError:
            print(f"skipping unparseable {f}", file=sys.stderr)
    return out


def worst_verdict(runs: list[dict], profile: str) -> str:
    """Worst verdict across runs. A machine that fails at 18:00 fails."""
    order = ["pass", "marginal", "unknown", "fail"]
    seen = [(r.get("verdict") or {}).get(profile) for r in runs]
    seen = [s for s in seen if s]
    if not seen:
        return "?"
    return max(seen, key=lambda v: order.index(v) if v in order else 0)


def spread(runs: list[dict], path: str) -> tuple[str, str]:
    """(median, worst) for a latency-like metric.

    'Worst' is the maximum, so only latency-shaped paths belong here -- passing
    a throughput metric would report the best value as the worst.
    """
    vals = [dig(r, path) for r in runs]
    vals = [v for v in vals if v is not None]
    if not vals:
        return ("-", "-")
    if len(vals) < MIN_RUNS_FOR_SPREAD:
        # Refuse to print a median of one or two points. The worst case is still
        # meaningful -- it happened -- so report that and mark the median absent.
        return ("-", fmt_us(max(vals)))
    return (fmt_us(statistics.median(vals)), fmt_us(max(vals)))


def hour_range(runs: list[dict]) -> str:
    hours = sorted({r["run"]["local_hour"] for r in runs
                    if dig(r, "run.local_hour") is not None})
    return ", ".join(f"{h:02d}h" for h in hours) if hours else "?"


def render_run_row(r: dict) -> str:
    v = r.get("verdict") or {}
    cells = [
        f"`{r['run']['host_id'][:6]}`",
        r["run"]["timestamp_utc"][:10],
        f"{r['run']['local_hour']:02d}h",
        fmt_us(dig(r, "disk.wal_fsync.p999_us")),
        fmt_us(dig(r, "disk.rand_read_8k.p99_us")),
        fmt_pct(dig(r, "cpu.steal_pct_under_load")),
        fmt_us(dig(r, "cpu.intrinsic_latency_max_us")),
        fmt_pct(dig(r, "disk.steady_state.degradation_pct")),
    ] + [MARK[v.get(p)] for p in PROFILES]
    return "| " + " | ".join(cells) + " |"


def main() -> int:
    runs = load_all()

    print("<!-- AUTOGENERATED by tools/render.py - do not edit. -->")
    print("<!-- Edit results/*.json and re-run: python3 tools/render.py > RESULTS.md -->")
    print()
    print("# Results")
    print()

    if not runs:
        print("No results submitted yet. See [CONTRIBUTING.md](CONTRIBUTING.md).")
        return 0

    hosts = {r["run"]["host_id"] for r in runs}
    provs = {r["provider"]["name"] for r in runs}
    print(f"{len(runs)} runs across {len(hosts)} machines at {len(provs)} providers.")
    print()
    print(DISCLAIMER)
    print()

    by_product = defaultdict(list)
    for r in runs:
        p = r["provider"]
        by_product[(p["name"], p["region"], p["product"])].append(r)

    # ---------------------------------------------------------------- summary
    print("## Summary")
    print()
    print("One row per product and region. `fsync p99.9` is the number that decides")
    print("whether a database is viable here, and the worst case matters more than the")
    print("median: your slowest commits are the ones users notice.")
    print()
    print("| Provider | Region | Product | Machines | Runs | fsync p99.9 med | fsync p99.9 worst | stall worst | pg | ts | redis | nuxt |")
    print("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for (name, region, product), rs in sorted(by_product.items()):
        n_hosts = len({r["run"]["host_id"] for r in rs})
        med, worst = spread(rs, "disk.wal_fsync.p999_us")
        _, stall = spread(rs, "cpu.intrinsic_latency_max_us")
        cells = [name, region, f"`{product}`", str(n_hosts), str(len(rs)),
                 med, worst, stall] + [MARK[worst_verdict(rs, p)] for p in PROFILES]
        print("| " + " | ".join(cells) + " |")
    print()
    print("Verdicts are the **worst** across all runs for that product. A machine that")
    print("passes at 03:00 and fails at 18:00 is a machine that fails.")
    print()

    # ----------------------------------------------------------------- detail
    print("## Detail")
    print()

    for (name, region, product), rs in sorted(by_product.items()):
        by_host = defaultdict(list)
        for r in rs:
            by_host[r["run"]["host_id"]].append(r)
        n_hosts = len(by_host)

        print(f"### {name} / {region} / `{product}`")
        print()

        meta = [f"{len(rs)} run{'s' if len(rs) != 1 else ''}",
                f"{n_hosts} machine{'s' if n_hosts != 1 else ''}"]
        price = dig(rs[0], "provider.price_eur_month")
        if price:
            meta.append(f"{price:.2f} EUR/mo")
        if dig(rs[0], "provider.storage_tier"):
            meta.append(f"storage: {rs[0]['provider']['storage_tier']}")
        boot = dig(rs[0], "disk.is_boot_volume")
        if boot is True:
            meta.append("**boot volume**")
        elif boot is False:
            meta.append("dedicated data volume")
        print(" - ".join(meta))
        print()

        # TIME VARIANCE: one machine, several hours.
        for hid, hrs in sorted(by_host.items()):
            if len(hrs) < 2:
                continue
            hrs.sort(key=lambda r: r["run"]["timestamp_utc"])
            med, worst = spread(hrs, "disk.wal_fsync.p999_us")
            print(f"**Machine `{hid[:6]}`** - {len(hrs)} runs at {hour_range(hrs)}")
            print()
            if len(hrs) < MIN_RUNS_FOR_SPREAD:
                print(f"Fewer than {MIN_RUNS_FOR_SPREAD} runs, so no spread is computed. "
                      f"Worst fsync p99.9 seen: {worst}.")
            else:
                print(f"fsync p99.9 across the day: median {med}, worst {worst}.")
                vals = [dig(r, "disk.wal_fsync.p999_us") for r in hrs]
                vals = [v for v in vals if v is not None]
                if vals and min(vals) and max(vals) / min(vals) >= 2:
                    print()
                    print(f"> {max(vals)/min(vals):.1f}x swing on the same machine depending on "
                          "the hour. That is a neighbour, not the hardware.")
            print()

        # HOST VARIANCE: several machines, same product.
        if n_hosts >= 2:
            print(f"**Across {n_hosts} machines**")
            print()
            per_host = {}
            for hid, hrs in by_host.items():
                vals = [dig(r, "disk.wal_fsync.p999_us") for r in hrs]
                vals = [v for v in vals if v is not None]
                if vals:
                    per_host[hid] = max(vals)
            vals = list(per_host.values())
            if len(vals) >= 2:
                lo, hi = min(vals), max(vals)
                factor = hi / lo if lo else 0
                line = f"Worst fsync p99.9 per machine ranges {fmt_us(lo)} to {fmt_us(hi)}"
                line += f" ({factor:.1f}x spread)." if factor >= 1.5 else "."
                print(line)
                if factor >= 2:
                    print()
                    print("> A 2x or larger spread between machines of the same product means")
                    print("> this fleet is not uniform. Which machine you get is luck.")
            print()

        print("<details>")
        print(f"<summary>All {len(rs)} run{'s' if len(rs) != 1 else ''}</summary>")
        print()
        print("| Machine | Date | Hour | fsync p99.9 | rand-read p99 | steal | stall max | steady drop | pg | ts | redis | nuxt |")
        print("|---|---|---|---|---|---|---|---|---|---|---|---|")
        for r in sorted(rs, key=lambda x: x["run"]["timestamp_utc"]):
            print(render_run_row(r))
        print()
        notes = [(r["run"]["host_id"][:6], r["run"]["timestamp_utc"][:10], r["run"]["notes"])
                 for r in sorted(rs, key=lambda x: x["run"]["timestamp_utc"])
                 if dig(r, "run.notes")]
        if notes:
            for hid, date, note in notes:
                print(f"- `{hid}` {date}: {note}")
            print()
        print("</details>")
        print()

    # --------------------------------------------------------------- failures
    print("## Why runs failed")
    print()
    print("Computed from [schema/thresholds.yaml](schema/thresholds.yaml), not written")
    print("by hand. Disagree with a verdict? The thing to argue about is the threshold.")
    print()
    reason_counts = defaultdict(int)
    for r in runs:
        for reason in (r.get("verdict") or {}).get("reasons", []):
            key = reason.split("=")[0].strip().rstrip(" (")
            reason_counts[key] += 1
    if reason_counts:
        print("| Failing rule | Runs affected |")
        print("|---|---|")
        for k, c in sorted(reason_counts.items(), key=lambda x: -x[1]):
            print(f"| {k} | {c} |")
    else:
        print("No failing rules across submitted runs.")
    print()

    print("---")
    print()
    print("## Raw data")
    print()
    print("Every number above comes from a JSON file under [`results/`](results/),")
    print("laid out as `results/<provider>/<region>/`. Nothing here is hand-written.")
    print("If a number looks wrong, open the file and check it.")
    print()
    print("`host_id` is a salted hash of the machine's `/etc/machine-id`. It links runs")
    print("on the same VM together and means nothing outside this dataset.")
    return 0


if __name__ == "__main__":
    sys.exit(main())